### PR TITLE
Unscented RTS Smoother and Missing Observations

### PR DESCRIPTION
**Pull request by JonnyCBB**
It's quite a big PR. I've basically only implemented the Missing observations algorithm that I mentioned in my email and the Unscented RTS smoother.

Your implementation for missing observations is used by default, mine is an option that the user can decide to use. The effects of the different implementations are included in the [example on the missing observations](https://github.com/JonnyCBB/StateSpace.jl/blob/master/examples/MissingObservationsExample.ipynb).

I've implemented the Unscented RTS Smoother for the additive noise case, although it can be extended to the augmented case. Again the results of this algorithm are included in the [UKF example with the van der pol oscillator](https://github.com/JonnyCBB/StateSpace.jl/blob/master/examples/UnscentedKalmanFilter_DampedOscillatorExample.ipynb).

I've updated the [README](https://github.com/JonnyCBB/StateSpace.jl/blob/master/README.md) and [Examples README](https://github.com/JonnyCBB/StateSpace.jl/blob/master/examples/README_examples.md) too. 

I haven't fully created documentation for the code so I'll get to this soon.

### CODE REVIEW

**Comment by ElOceanografo** [comment]
This breaks one of the sanity checks in test_KF.jl...the likelihood of the smoothed state is not higher than the likelihood of the filtered state.  Do you mind checking the changes to the updating and filtering functions?

**Comment by JonnyCBB** [comment]
Yes sorry about that. I commented out the lines of code for the log likelihood calculation while I was developing the URTS smoother algorithm and forgot to write the likelihood calculation once the code was written (so it was giving a value of 0.0 for the likelihood of the smoother). 
I have sorted out the calculation now.

**Comment by JonnyCBB** [comment]
So my previous comment was with regards to the smoother for the UKF. I didn't realise you mean the smoother for the linear filter (I should've checked - sorry). 

I've sorted the problem now but there is a minor issue:
In the original "filter" method that you wrote, the likelihood calculation is different for the first state that you calculate than for all subsequent states. I wasn't sure if this was intentional or if it was a bug. I have changed my code so I calculate the exact log likelihood values as the previous implementation (that passed the tests). But you might want to have a look at it to make sure that it is correct...... I suspect it's not.

**Comment by ElOceanografo** [comment]
Sorry this took so long to merge, I'm in a busy patch...

**Pull request closed without merging**
